### PR TITLE
Add compatibilty for laravel (illuminate/support) 5.8 & 6.0

### PR DESCRIPTION
**Pull request by stephenjude**

### CODE REVIEW

**Comment by bosunski** [comment]
Cool!. Been waiting for this 😁.
Can you please provide a little description, especially on how I can test this? Then we'll merge

**Comment by stephenjude** [comment]
Updating travis like this
` - php: 7.1
      env: LARAVEL='5.8.*' 
`
[Check out this post for more details ](https://www.tjmiller.me/blog/verifying-laravel-version-compatibility/)

**Comment by stephenjude** [comment]
The test suite needs to run with the supported php and illuminate versions.

**Comment by stephenjude** [comment]
All tests are passing in correspondence with all Laravel  versions and the required php version. I think we are good to merge

**Pull request merged**
